### ISSUE TITLE
Receiving error in bin/render-stamp.js on line 20

### ISSUE THREAD

**Issue by Drumsticks** [s-a/video-datetime-stamp#1]
Hello, I'm receiving the following error when running the following line:
`mocha test/test`

The following error is what I receive and I am not sure why.
$ mocha test/test

  render a time stamp to MP4
Rendering F:\videostamp\video\BigBuckBunny_320x180.mp4 to F:\videostamp\video\BigBuckBunny_320x180.stamped.mp4
font: font/OpenSans-Regular.ttf
video end Wednesday, July 15th 2015, 12:58:34 pm a year ago
F:\videostamp\bin\render-stamp.js:20
        var duration =  (shell.exec(cmd).output.replace(/\n/g, "").replace(/\r/g, "")
                                               ^
TypeError: Cannot read property 'replace' of undefined
    at getVideoDuration (F:\videostamp\bin\render-stamp.js:20:41)
    at convertVideo (F:\videostamp\bin\render-stamp.js:77:17)
    at Object.<anonymous> (F:\videostamp\bin\render-stamp.js:107:2)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
    1) should exit with error code 0
    √ should exists an output file

  1 passing (2s)
  1 failing

  1) render a time stamp to MP4 should exit with error code 0:

      AssertionError: expected 1 to be 0
      + expected - actual

      -1
      +0

      at Assertion.fail (F:\videostamp\node_modules\should\cjs\should.js:326:17)
      at Assertion.Object.defineProperty.value (F:\videostamp\node_modules\should\cjs\should.js:398:19)
      at Context.<anonymous> (F:\videostamp\test\test.js:20:22)
      at callFn (C:\Users\asdf\AppData\Roaming\npm\node_modules\mocha\lib\runnable.js:326:21)
      at Test.Runnable.run (C:\Users\asdf\AppData\Roaming\npm\node_modules\mocha\lib\runnable.js:319:7)
      at Runner.runTest (C:\Users\asdf\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:422:10)
      at C:\Users\asdf\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:528:12
      at next (C:\Users\asdf\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:342:14)
      at C:\Users\asdf\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:352:7
      at next (C:\Users\asdf\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:284:14)
      at Immediate._onImmediate (C:\Users\asdf\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:320:5)

**Comment by s-a** [comment]
Is ffmpeg installed and in your path?
You could also try to debug with iron-node. ```npm i -g iron-node``` 

```iron-node node_modules/mocha/bin/_mocha````

**Comment by Drumsticks** [comment]
Hi s-a,

It is very likely that if I do need to install ffmpeg (I was incorrectly thinking everything was bundled together), then I will need to do that.  I am rather new to Node.js, so I am pretty much flying by the seat of my pants with this endeavor.

I will look into iron-node as well.

Thank you!
Ryan

**Comment by s-a** [comment]
Well the Readme is not good. It is not bundled so you need to install it and add it to your systems path so that is global available in your terminal. However it seems to be available on your system.
Maybe a too old ffmpg Version. If you do not know how to debug you can try to execute shell command  
https://github.com/s-a/video-datetime-stamp/blob/master/bin/render-stamp.js#L19 manually . It should output the video duration but seems to return null in node.

**Comment by s-a** [comment]
I fixed a bug but the call stil did not work . 

This is the command it generates.

```)ffmpeg "C:\git\video-datetime-stamp\video\BigBuckBunny_320x180.mp4" -f MP4 -vf "drawtext=expansion=strftime: fontfile=font/OpenSans-Regular.ttf: text='%a %d\.%m\.%Y / %H\:%M\:%S': x=10:y=10: fontcolor=white: box=1: boxcolor=0x00000000@1: basetime=1466750907099000" -t 2 -preset ultrafast -y C:\git\video-datetime-stamp\video\BigBuckBunny_320x180.stamped.mp4```


But it fails with ```Output file #0 does not contain any stream```. :/

**Comment by s-a** [comment]
By the way I downloaded ffmpeg from here https://ffmpeg.zeranoe.com/builds/win64/static/ffmpeg-20160624-6935aaa-win64-static.zip
